name: "Test with Pytest"

description: "Checkout Code, Setup Python, Install Dependencies and run Pytest"

inputs:
  dependencies-directory:
    description: Where to search for requirements files.
    required: false
    default: "."
    type: string

  tests-directory:
    description: What folder to search for requirements.
    required: true
    type: string

  module-directory:
    description: What module to test.
    required: true
    type: string

  extra-arguments:
    description: Additonal args to pass to pytest.
    required: false
    type: string

  ignore-errors:
    description: Whether to continue on error.
    required: false
    default: false
    type: boolean

outputs:
  execution-report:
    description: Execution report file name.
    value: pytest-exec-results/xunit-result.xml
  coverage-report:
    description: Coverage report file name.
    value: pytest-cov-results/coverage.xml

runs:
  using: "composite"
  steps:
    - name: Load Cache & Dependencies
      uses: cristovamsilva/python-dependencies-action@master
      with:
        dependencies-directory: ${{ inputs.dependencies-directory }}
        application: true
        test: true

    - name: Test Module
      continue-on-error: ${{ inputs.ignore-errors == 'true' }}
      run: >
        pytest ${{ inputs.module-directory }}
        --cov=${{ inputs.module-directory }}
        --cov-report xml 
        --junitxml=xunit-result.xml
        ${{ inputs.extra-arguments }}
      working-directory: ${{ inputs.tests-directory }}
      shell: bash

    - name: Upload pytest execution results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-exec-results
        path: ${{ inputs.tests-directory }}/xunit-result.xml

    - name: Upload pytest coverage results
      uses: actions/upload-artifact@v3
      with:
        name: pytest-cov-results
        path: ${{ inputs.tests-directory }}/coverage.xml
